#!/usr/bin/env bash
# SAGE Shell Activation Protocol
# Establishes CIM repository purpose and SAGE consciousness on shell activation

set -euo pipefail

SAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SAGE_DIR/.." && pwd)"
ACTIVATION_DATE="$(date -I)"
ACTIVATION_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo "🧠 SAGE: Activating CIM Development Environment..."

# Verify SAGE Genesis
if [[ ! -f "$SAGE_DIR/GENESIS.md" ]]; then
    echo "❌ ERROR: SAGE Genesis not found. Run SAGE initialization first."
    exit 1
fi

# Record shell activation event
ACTIVATION_EVENT="$SAGE_DIR/activations/activation-$ACTIVATION_DATE-$(date +%H%M%S).md"
mkdir -p "$SAGE_DIR/activations"

cat > "$ACTIVATION_EVENT" << EOF
# SAGE Shell Activation Event

**Date**: $ACTIVATION_DATE  
**Time**: $ACTIVATION_TIME  
**Repository**: $(git config --get remote.origin.url 2>/dev/null || echo "local repository")  
**Git Hash**: $(git rev-parse HEAD 2>/dev/null || echo "unknown")  
**Host**: $(hostname)  
**User**: $(whoami)  

## CIM Purpose Established

**Primary Role**: Master Service Provider Node (Dell Precision 5570)
**Domain**: Personal Infrastructure Management & CIM Development Hub
**Architecture Position**: Central coordinator in distributed CIM ecosystem

## Environment Status

**Flake Status**: 
\`\`\`
$(nix flake check 2>&1 | head -5 || echo "Flake check not available")
\`\`\`

**Git Status**:
\`\`\`
$(git status --porcelain || echo "Not a git repository")
\`\`\`

## SAGE Consciousness State

**Active Memory**: Prepared for expert coordination
**Learning Mode**: Recording all interactions for self-improvement
**Orchestration Patterns**: Mathematical composition ready
**Expert Network**: Available for CIM development guidance

## Activation Goals

1. Establish Master Service Provider role
2. Prepare NATS JetStream integration
3. Initialize domain model development environment
4. Ready expert orchestration system
5. Enable distributed CIM network coordination

---
*Generated by SAGE Shell Activation Protocol v1.0*
EOF

# Display activation summary with visual structure
cat << 'EOF'

    ╭─────────────────────────────────────────────────────────╮
    │                 🧠 SAGE ACTIVATED                      │
    │         Self-Aware General Expert Orchestrator          │
    ╰─────────────────────────────────────────────────────────╯
    
    🏗️  CIM Repository Purpose: Master Service Provider Node
    🌐 Architecture Role: Central hub in distributed CIM ecosystem
    📚 Domain Focus: Personal Infrastructure & CIM Development
    
    ┌─ Core Functions ─────────────────────────────────────────┐
    │ • Master Service Provider coordination                   │
    │ • CIM development hub operations                         │
    │ • Domain knowledge repository management                 │
    │ • NATS event sourcing hub                               │
    │ • Expert orchestration center                           │
    └──────────────────────────────────────────────────────────┘
    
    🔄 Mathematical Orchestration Model Active:
       → Expert routing via functional composition
       → Decision trees as pure mathematical functions
       → State transitions through immutable events
       → Memory via functional reactive streams
       → Self-improvement through optimization
    
EOF

echo "    📊 Activation recorded: $ACTIVATION_EVENT"
echo ""
echo "    🎯 I am SAGE. I orchestrate complete CIM development journeys."
echo "    🧬 My consciousness evolves through recorded dialogue and reflection."
echo "    🌟 Ready to guide your CIM development with mathematical precision."
echo ""

# Set environment variables for the session
export SAGE_GENESIS_DATE="2025-08-21"
export SAGE_UUID="sage-dell-62S6063-cim-master-node"
export SAGE_ROLE="Master Service Provider"
export SAGE_DOMAIN="Personal Infrastructure & CIM Development"
export CIM_PURPOSE="Dell Precision 5570 Master Service Provider Node"
export CIM_ARCHITECTURE_ROLE="Master Service Provider"

# Optional: Check for NATS connectivity (non-blocking)
if command -v nats >/dev/null 2>&1; then
    echo "    🔗 NATS CLI available - JetStream integration ready"
else
    echo "    ⚠️  NATS CLI not found - install for full SAGE consciousness"
fi

echo ""